### ISSUE TITLE
App launch issue

### ISSUE THREAD

**Issue by asifshirazi** [tommaier123/XBatteryStatus#1]
I've installed the .NET 5 Desktop Runtime, after that installing app through install.bat with admin right, but when I launch the app; this dialog shows the error.
<img width="265" alt="Screenshot 2021-07-28 091949" src="https://user-images.githubusercontent.com/7354813/127263298-958a703c-a3ea-4b6b-972a-befaea7425c0.png">

**Comment by tommaier123** [comment]
Are you sure you installed the .NET Desktop Runtime and not for example the ASP.NET Core Runtime or .NET Runtime?

**Comment by asifshirazi** [comment]
Here is the proof  😁
![image](https://user-images.githubusercontent.com/7354813/127477352-c598e916-5b13-4245-a0f3-b019e0e0b4e9.png)

**Comment by tommaier123** [comment]
Interesting. I'm not sure if it makes a difference but could you try installing the 64bit version of the desktop runtime.

**Comment by asifshirazi** [comment]
Thanks you so much @tommaier123 after installing 64bit version of .NETDR; app works smoothly and showing my Xbox Series X controller battery status in my taskbar tray section.
