### ISSUE TITLE
White icon with white Win11 theme

### ISSUE THREAD

**Issue by fernandog** [tommaier123/XBatteryStatus#15]
![Fs4nvHBhO6](https://github.com/tommaier123/XBatteryStatus/assets/2620870/e007136b-b99b-426f-99d6-3f5659dbf00d)

![image](https://github.com/tommaier123/XBatteryStatus/assets/2620870/7c96d748-55d4-43d8-b1cc-1c25c2af90d4)

**Comment by tommaier123** [comment]
This is fixed in the [V1.1.0 beta release](https://github.com/tommaier123/XBatteryStatus/releases/tag/V1.1.0)
