### ISSUE TITLE
Tray icon disappeared

### ISSUE THREAD

**Issue by scoony** [tommaier123/XBatteryStatus#16]
I've tried your app but sadly the tray  icon showed up for few seconds and disappeared (was still running in the background apparently), I'm running Windows 11 and I've got the official xbox USB adapter.

**Comment by tommaier123** [comment]
Did you have the controller connected?
It will hide itself if bluetooth is turned off or if no controller is connected.

**Comment by CM630** [comment]
I have the same problem.
After I run the app it shows: “XBatteryStatus: No paired controller with battery service found.”, which is not true.
Then it disappears.
My device is headphones “MusicSound”, model BT8026A.

Also, I see no reason why the icon should disappear when no device is connected - should not it start indicating when a device is switched from  Off to On?

**Comment by tommaier123** [comment]
It only works for bluetooth gamepads not headphones.
The reason it disappears is to keep the tray clean when it is not needed.

**Comment by stealthrabbi** [comment]
I'm on Windows 10. This app used to work. The Icon either is completely hidden, or just has a grey icon without showing the battery status. Right clicking it just has the option of "Exit". There is no indicator for the battery status and no sound that plays as it used to. 

I am using an Xbox One controller connected via bluetooth.

**Comment by tommaier123** [comment]
That is strange, it should never really be grey when it is in the tray.
The only thing I changed recently is that it detects when Bluetooth is turned on/off, otherwise it should work as it used to.
Can you try turning Bluetooth off and on.

**Comment by tommaier123** [comment]
In the latest version there is a toggle to select if the tray icon hides itself or not.
If your controller is not recognized feel free to open a new issue.
