### ISSUE TITLE
Light/Dark mode autodetection uses in-window colour instead of taskbar

### ISSUE THREAD

**Issue by Touchebag** [tommaier123/XBatteryStatus#17]
The light/dark mode colour is chosen based on the selection in Windows settings. This makes the icon unusable if you want light mode windows but a dark taskbar (i.e. default in Windows 10) as the icon will be black on black and essentially invisible.

Would it be possible to add a manual setting of icon colour?

**Comment by tommaier123** [comment]
I didn't know you could change it separately. Adding a setting should be easy enough

**Comment by tommaier123** [comment]
This feature was added to the latest release

**Comment by Touchebag** [comment]
Can confirm it works after restarting the application
