### ISSUE TITLE
Its possible to add more features?

### ISSUE THREAD

**Issue by hectorevil** [tommaier123/XBatteryStatus#18]
Like other  projects like 

https://github.com/NiyaShy/XB1ControllerBatteryIndicator

 - Show on tray icon when battery its full and chargin.
 - Possibility to ad new sounds

**Comment by tommaier123** [comment]
- It would be possible to show if a controller is connected via USB but I don't think there is a way to get the battery level or even if it is charging.
- The sounds is not controlled by the app, tis the windows notification sound.

**Comment by tommaier123** [comment]
Duplicate of #6
