### ISSUE TITLE
Show numeric battery level in icon

### ISSUE THREAD

**Issue by ximmo** [tommaier123/XBatteryStatus#19]
Is it possible to have the battery level in numbers in the icon itself, so you dont have to hover over it to see the exact level?
That would be a handy maybe optional setting I would appreciate.

**Comment by tommaier123** [comment]
Something like this would be possible with some manipulation of the bitmap. I'm not sure if I like how it looks though.
![Numeric](https://github.com/tommaier123/XBatteryStatus/assets/40432491/5d6b7a7c-8983-4b66-808e-dfce983e5f19)

**Comment by ximmo** [comment]
Oh nice, to me it doesn't look thatbad.
Hmm, you could get completely get rid of the battery level behind the numbers, makes it a bit hard to read, or you could make the level into an outline,
Hell, you could get rid of the battery icon and put the number into the controller or something like that, I don't know, completely up to you.
Either way, I would be very happy just with what you already made.

**Comment by tommaier123** [comment]
I'll see what I can do. It's more pixelart than anything

**Comment by tommaier123** [comment]
Implemented in release V1.3.2
