### ISSUE TITLE
How to unistall this program

### ISSUE THREAD

**Issue by JkohlerBeans** [tommaier123/XBatteryStatus#2]
This program does not show up in programs and features. How do you remove it?

**Comment by tommaier123** [comment]
You can disable it in the startup section of the task manager or uninstall it by deleting it from the autostart folder. But good point. I should add an uninstall script.

**Comment by JkohlerBeans** [comment]
Ok, good to know. I wasn't sure if there was anything in the registry or other stuff that's hard to remove. Thanks for the reply.
