### ISSUE TITLE
1.3.2 Trojan

### ISSUE THREAD

**Issue by AdamBridges** [tommaier123/XBatteryStatus#25]
Windows anti-virus flagged version 1.3.2 as a Trojan:

![image](https://github.com/tommaier123/XBatteryStatus/assets/55845532/a06fd16b-80eb-4143-a419-b59937b73fea)

**Comment by tommaier123** [comment]
Unfortunately Windows Defender has been getting a lot of false positives for Wacatac. There is not really much that can be done to avoid this. The only real solution would be to get a code signing certificate but that costs hundreds of dollars per year.
I am working to get 1.3.2 on winget  and also want to publish as an app on the Microsoft store. These options might be less likely to trigger Widows Defender. Until then you can try installing it again in a few days. Usually is resolved relatively quickly.

**Comment by AdamBridges** [comment]
Sounds good. Thanks for clarifying.
