### ISSUE TITLE
Wrong file version

### ISSUE THREAD

**Issue by fernandog** [tommaier123/XBatteryStatus#27]
The .exe file is 1.2.1, but the systray icon and windows installed programs says its 1.3.2

![image](https://github.com/tommaier123/XBatteryStatus/assets/2620870/e2027311-ea39-4519-a099-5e8dd9d5dae1)

**Comment by tommaier123** [comment]
Thanks for the info. I forgot to increment the version for the exe. That shouldn't affect anything, but I have updated the release.

**Comment by fernandog** [comment]
I noticed because I have an app that's checks for outdated apps and it checks the .exe file version. thanks

**Comment by tommaier123** [comment]
Like your own package manager. Sounds cool.

**Comment by fernandog** [comment]
It's a free one: Ucheck. I also use WingetUI.
