### ISSUE TITLE
Asking for .net installation w/o specifying which version

### ISSUE THREAD

**Issue by rosejvarela** [tommaier123/XBatteryStatus#28]
Hello, I'm trying to install xbatterystatus.msi and when trying to run it it asks if I want to install .net, but doesn't specify which version it wants and doesn't seem to check for the version I already have installed (4.8).

Would really appreciate some help into knowing how I can get this working please. 

Thank you beforehand!
![image_2024-03-23_113741084](https://github.com/tommaier123/XBatteryStatus/assets/164648301/45ee49e8-f96d-4d7b-89af-b11e9d3ce2dd)

**Comment by tommaier123** [comment]
It needs the [.NET 5 Desktop Runtime (x64)](https://dotnet.microsoft.com/download/dotnet/5.0)
If you already have a compatible runtime it would use that.
I have added the info back in the readme, it got lost when I changed the isntaller to automatically install the prerequisites.
