### ISSUE TITLE
GDI object memory leak

### ISSUE THREAD

**Issue by stefan-gha** [tommaier123/XBatteryStatus#29]
There seems to be a memory leak in XBatteryStatus w.r.t. GDI objects.

After running XBatteryStatus for a while it will crash with the following exception:

System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Bitmap.GetHicon()
   at XBatteryStatus.MyApplicationContext.GetIcon(Int32 val, String s) in C:\Users\Max\source\repos\tommaier123\XBatteryStatus\XBatteryStatus\MyApplicationContext.cs:line 461
   at XBatteryStatus.MyApplicationContext.ReadBattery() in C:\Users\Max\source\repos\tommaier123\XBatteryStatus\XBatteryStatus\MyApplicationContext.cs:line 331
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)

Tracking the number of GDI objects in task manager show it steadily increasing. Currently it is reporting 4,517 GDI objects for me, which is more then any other program by a large margin. To my understanding, Windows will limit the number of handles at some point, causing the exception above.

Could this exception be due to the handle given by System.Drawing.Bitmap.GetHicon() never being destroyed? I don't see any calls to DestroyIcon in the code. There might be other leaks, but this is my primary suspect.

For reference see the example code snippet calling DestroyIcon:
https://learn.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.gethicon?view=net-8.0

And the issue mentioned more explicitly here:
https://stackoverflow.com/questions/30979653/icon-fromhandle-should-i-dispose-it-or-call-destroyicon

Love the project. Hope it can be fixed.

**Comment by tommaier123** [comment]
Good catch. Your analysis was on point. Thanks for the detailed bug report.
